### ISSUE TITLE
Overflow problem with embedding Facebook

### ISSUE THREAD

**Issue by masterqwerty** [byu-oit/news-website#132]
Whenever a Facebook post is embedded, it's width will stay fixed. This is a problem when mobile sizes are used, and then you have to scroll to the sides to see the full post.

**Comment by katrialesser** [comment]
Facebook embed always includes a width="" attribute inline. We can't override that with css.
The thing is, if the width is set inline like that, the only way to really override it is to use js and change the width attribute.
Which gets messy because of the structure of that iframe and if facebook changed it's code our fix could break later anyway.
so last time we told Joe that and he said we'd not worry about it for now. We could return to this and possibly come up with a cleaner way to target and use js in phase II maybe.
